services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 21522525@
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: 21522525@
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mariadb-config:/etc/mysql/conf.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 21522525@
      UPLOAD_LIMIT: 200M
    ports:
      - "8080:80"
    depends_on:
      - db

  apache:
    image: httpd:latest
    ports:
      - "80:80"
    volumes:
      - ./public-html:/usr/local/apache2/htdocs/

volumes:
  db_data: