name: Deploy Website to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH private key (duwin.pem) from a secret
      - name: Write duwin.pem to a file
        run: |
          echo "${{ secrets.DUWIN_PEM }}" > duwin.pem
          chmod 600 duwin.pem

      # Step 3: SCP to copy files to the server
      - name: Deploy using SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}             # Server IP or hostname
          username: ${{ secrets.USERNAME }}     # SSH username
          key_path: ./duwin.pem                 # Path to the private key (duwin.pem)
          source: ./*                           # Files to copy
          target: /var/www/your_project          # Target directory on the server
          port: 22                              # SSH port

      # Step 4: Clean up the private key
      - name: Clean up private key
        run: rm -f duwin.pem
