name: Deploy Website to Server via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH key for authentication
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/duwin.pem
          chmod 600 ~/.ssh/duwin.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Step 3: Deploy using SSH (Copy files or execute commands)
      - name: Deploy using SSH
        run: |
          ssh -i ~/.ssh/duwin.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /var/www/your_project
            git pull origin main
            npm install
            pm2 restart all
          EOF

      # Step 4: Clean up private key
      - name: Clean up SSH key
        run: rm -f ~/.ssh/duwin.pem
