name: Deploy Website to Server

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up the SSH private key
      - name: Set up SSH private key
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      # Step 3: Copy files to the server
      - name: Copy files to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}               # Server IP or domain
          username: ${{ secrets.USERNAME }}       # SSH user
          key_path: ./private_key.pem             # Path to the private key
          source: ./*                             # Files to copy
          target: /tmp/${{ secrets.SITE_NAME }}   # Temporary target on the server
          port: 22                                # SSH port

      # Step 4: Run the deployment script on the server
      - name: Deploy the website using custom script
        run: |
          ssh -i private_key.pem ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
          # Move the uploaded files to the final directory and deploy
          sudo /path/to/deploy_site.sh ${{ secrets.SITE_NAME }} ${{ secrets.DOMAIN }} ${{ secrets.PORT }}
          EOF

      # Step 5: Clean up private key
      - name: Clean up private key
        run: |
          rm -f private_key.pem
